// flow-typed signature: d648ee4648f68ca8fb10cfa7f1804760
// flow-typed version: <<STUB>>/@elastic/elasticsearch_v^7.3.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@elastic/elasticsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@elastic/elasticsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@elastic/elasticsearch/api/api/bulk' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.aliases' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.allocation' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.count' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.fielddata' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.health' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.help' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.indices' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.master' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.nodeattrs' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.nodes' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.pending_tasks' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.plugins' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.recovery' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.repositories' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.segments' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.shards' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.snapshots' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.tasks' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.templates' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cat.thread_pool' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.delete_auto_follow_pattern' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.follow_info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.follow_stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.follow' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.forget_follower' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.get_auto_follow_pattern' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.pause_follow' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.put_auto_follow_pattern' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.resume_follow' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ccr.unfollow' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/clear_scroll' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.allocation_explain' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.get_settings' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.health' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.pending_tasks' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.put_settings' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.remote_info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.reroute' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.state' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/cluster.stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/count' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/create' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.delete_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform_stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.preview_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.put_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.start_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/data_frame.stop_data_frame_transform' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/delete_by_query_rethrottle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/delete_by_query' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/delete_script' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/delete' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/exists_source' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/exists' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/explain' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/field_caps' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/get_script' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/get_source' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/get' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/graph.explore' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.delete_lifecycle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.explain_lifecycle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.get_lifecycle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.get_status' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.move_to_step' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.put_lifecycle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.remove_policy' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.retry' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.start' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ilm.stop' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.analyze' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.clear_cache' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.close' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.create' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.delete_alias' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.delete_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.delete' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.exists_alias' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.exists_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.exists_type' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.exists' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.flush_synced' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.flush' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.forcemerge' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.freeze' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_alias' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_field_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_settings' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get_upgrade' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.get' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.open' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.put_alias' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.put_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.put_settings' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.put_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.recovery' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.refresh' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.reload_search_analyzers' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.rollover' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.segments' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.shard_stores' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.shrink' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.split' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.unfreeze' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.update_aliases' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.upgrade' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/indices.validate_query' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ingest.delete_pipeline' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ingest.get_pipeline' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ingest.processor_grok' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ingest.put_pipeline' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ingest.simulate' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.delete' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.get_basic_status' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.get_trial_status' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.get' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.post_start_basic' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.post_start_trial' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/license.post' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/mget' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/migration.deprecations' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.close_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_calendar_event' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_calendar_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_calendar' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_data_frame_analytics' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_expired_data' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_filter' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_forecast' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.delete_model_snapshot' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.evaluate_data_frame' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.find_file_structure' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.flush_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.forecast' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_buckets' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_calendar_events' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_calendars' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_categories' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_data_frame_analytics_stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_data_frame_analytics' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_datafeed_stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_datafeeds' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_filters' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_influencers' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_job_stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_jobs' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_model_snapshots' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_overall_buckets' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.get_records' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.open_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.post_calendar_events' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.post_data' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.preview_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_calendar_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_calendar' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_data_frame_analytics' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_filter' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.put_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.revert_model_snapshot' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.set_upgrade_mode' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.start_data_frame_analytics' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.start_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.stop_data_frame_analytics' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.stop_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.update_datafeed' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.update_filter' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.update_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.update_model_snapshot' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.validate_detector' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ml.validate' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/monitoring.bulk' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/msearch_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/msearch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/mtermvectors' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/nodes.hot_threads' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/nodes.info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/nodes.reload_secure_settings' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/nodes.stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/nodes.usage' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/put_script' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rank_eval' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/reindex_rethrottle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/reindex' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/render_search_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.delete_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.get_jobs' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.get_rollup_caps' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.get_rollup_index_caps' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.put_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.rollup_search' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.start_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/rollup.stop_job' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/scripts_painless_execute' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/scroll' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/search_shards' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/search_template' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/search' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.authenticate' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.change_password' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.clear_cached_realms' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.clear_cached_roles' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.create_api_key' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.delete_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.delete_role_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.delete_role' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.delete_user' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.disable_user' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.enable_user' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_api_key' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_builtin_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_role_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_role' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_token' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_user_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.get_user' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.has_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.invalidate_api_key' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.invalidate_token' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.put_privileges' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.put_role_mapping' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.put_role' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/security.put_user' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.create_repository' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.create' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.delete_repository' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.delete' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.get_repository' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.get' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.restore' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.status' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/snapshot.verify_repository' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/sql.clear_cursor' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/sql.query' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/sql.translate' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/ssl.certificates' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/tasks.cancel' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/tasks.get' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/tasks.list' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/termvectors' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/update_by_query_rethrottle' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/update_by_query' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/update' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.ack_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.activate_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.deactivate_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.delete_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.execute_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.get_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.put_watch' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.start' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.stats' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/watcher.stop' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/xpack.info' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api/api/xpack.usage' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/api' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/Connection' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/errors' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/pool/BaseConnectionPool' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/pool/CloudConnectionPool' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/pool/ConnectionPool' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/pool' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/Serializer' {
  declare module.exports: any;
}

declare module '@elastic/elasticsearch/lib/Transport' {
  declare module.exports: any;
}

// Filename aliases
declare module '@elastic/elasticsearch/api/api/bulk.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/bulk'>;
}
declare module '@elastic/elasticsearch/api/api/cat.aliases.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.aliases'>;
}
declare module '@elastic/elasticsearch/api/api/cat.allocation.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.allocation'>;
}
declare module '@elastic/elasticsearch/api/api/cat.count.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.count'>;
}
declare module '@elastic/elasticsearch/api/api/cat.fielddata.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.fielddata'>;
}
declare module '@elastic/elasticsearch/api/api/cat.health.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.health'>;
}
declare module '@elastic/elasticsearch/api/api/cat.help.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.help'>;
}
declare module '@elastic/elasticsearch/api/api/cat.indices.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.indices'>;
}
declare module '@elastic/elasticsearch/api/api/cat.master.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.master'>;
}
declare module '@elastic/elasticsearch/api/api/cat.nodeattrs.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.nodeattrs'>;
}
declare module '@elastic/elasticsearch/api/api/cat.nodes.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.nodes'>;
}
declare module '@elastic/elasticsearch/api/api/cat.pending_tasks.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.pending_tasks'>;
}
declare module '@elastic/elasticsearch/api/api/cat.plugins.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.plugins'>;
}
declare module '@elastic/elasticsearch/api/api/cat.recovery.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.recovery'>;
}
declare module '@elastic/elasticsearch/api/api/cat.repositories.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.repositories'>;
}
declare module '@elastic/elasticsearch/api/api/cat.segments.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.segments'>;
}
declare module '@elastic/elasticsearch/api/api/cat.shards.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.shards'>;
}
declare module '@elastic/elasticsearch/api/api/cat.snapshots.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.snapshots'>;
}
declare module '@elastic/elasticsearch/api/api/cat.tasks.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.tasks'>;
}
declare module '@elastic/elasticsearch/api/api/cat.templates.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.templates'>;
}
declare module '@elastic/elasticsearch/api/api/cat.thread_pool.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cat.thread_pool'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.delete_auto_follow_pattern.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.delete_auto_follow_pattern'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.follow_info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.follow_info'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.follow_stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.follow_stats'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.follow.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.follow'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.forget_follower.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.forget_follower'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.get_auto_follow_pattern.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.get_auto_follow_pattern'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.pause_follow.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.pause_follow'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.put_auto_follow_pattern.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.put_auto_follow_pattern'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.resume_follow.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.resume_follow'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.stats'>;
}
declare module '@elastic/elasticsearch/api/api/ccr.unfollow.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ccr.unfollow'>;
}
declare module '@elastic/elasticsearch/api/api/clear_scroll.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/clear_scroll'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.allocation_explain.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.allocation_explain'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.get_settings.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.get_settings'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.health.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.health'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.pending_tasks.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.pending_tasks'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.put_settings.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.put_settings'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.remote_info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.remote_info'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.reroute.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.reroute'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.state.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.state'>;
}
declare module '@elastic/elasticsearch/api/api/cluster.stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/cluster.stats'>;
}
declare module '@elastic/elasticsearch/api/api/count.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/count'>;
}
declare module '@elastic/elasticsearch/api/api/create.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/create'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.delete_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.delete_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform_stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform_stats'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.get_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.preview_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.preview_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.put_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.put_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.start_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.start_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/data_frame.stop_data_frame_transform.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/data_frame.stop_data_frame_transform'>;
}
declare module '@elastic/elasticsearch/api/api/delete_by_query_rethrottle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/delete_by_query_rethrottle'>;
}
declare module '@elastic/elasticsearch/api/api/delete_by_query.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/delete_by_query'>;
}
declare module '@elastic/elasticsearch/api/api/delete_script.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/delete_script'>;
}
declare module '@elastic/elasticsearch/api/api/delete.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/delete'>;
}
declare module '@elastic/elasticsearch/api/api/exists_source.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/exists_source'>;
}
declare module '@elastic/elasticsearch/api/api/exists.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/exists'>;
}
declare module '@elastic/elasticsearch/api/api/explain.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/explain'>;
}
declare module '@elastic/elasticsearch/api/api/field_caps.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/field_caps'>;
}
declare module '@elastic/elasticsearch/api/api/get_script.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/get_script'>;
}
declare module '@elastic/elasticsearch/api/api/get_source.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/get_source'>;
}
declare module '@elastic/elasticsearch/api/api/get.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/get'>;
}
declare module '@elastic/elasticsearch/api/api/graph.explore.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/graph.explore'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.delete_lifecycle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.delete_lifecycle'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.explain_lifecycle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.explain_lifecycle'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.get_lifecycle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.get_lifecycle'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.get_status.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.get_status'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.move_to_step.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.move_to_step'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.put_lifecycle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.put_lifecycle'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.remove_policy.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.remove_policy'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.retry.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.retry'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.start.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.start'>;
}
declare module '@elastic/elasticsearch/api/api/ilm.stop.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ilm.stop'>;
}
declare module '@elastic/elasticsearch/api/api/index' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api'>;
}
declare module '@elastic/elasticsearch/api/api/index.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api'>;
}
declare module '@elastic/elasticsearch/api/api/indices.analyze.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.analyze'>;
}
declare module '@elastic/elasticsearch/api/api/indices.clear_cache.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.clear_cache'>;
}
declare module '@elastic/elasticsearch/api/api/indices.close.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.close'>;
}
declare module '@elastic/elasticsearch/api/api/indices.create.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.create'>;
}
declare module '@elastic/elasticsearch/api/api/indices.delete_alias.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.delete_alias'>;
}
declare module '@elastic/elasticsearch/api/api/indices.delete_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.delete_template'>;
}
declare module '@elastic/elasticsearch/api/api/indices.delete.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.delete'>;
}
declare module '@elastic/elasticsearch/api/api/indices.exists_alias.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.exists_alias'>;
}
declare module '@elastic/elasticsearch/api/api/indices.exists_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.exists_template'>;
}
declare module '@elastic/elasticsearch/api/api/indices.exists_type.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.exists_type'>;
}
declare module '@elastic/elasticsearch/api/api/indices.exists.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.exists'>;
}
declare module '@elastic/elasticsearch/api/api/indices.flush_synced.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.flush_synced'>;
}
declare module '@elastic/elasticsearch/api/api/indices.flush.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.flush'>;
}
declare module '@elastic/elasticsearch/api/api/indices.forcemerge.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.forcemerge'>;
}
declare module '@elastic/elasticsearch/api/api/indices.freeze.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.freeze'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_alias.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_alias'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_field_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_field_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_settings.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_settings'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_template'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get_upgrade.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get_upgrade'>;
}
declare module '@elastic/elasticsearch/api/api/indices.get.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.get'>;
}
declare module '@elastic/elasticsearch/api/api/indices.open.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.open'>;
}
declare module '@elastic/elasticsearch/api/api/indices.put_alias.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.put_alias'>;
}
declare module '@elastic/elasticsearch/api/api/indices.put_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.put_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/indices.put_settings.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.put_settings'>;
}
declare module '@elastic/elasticsearch/api/api/indices.put_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.put_template'>;
}
declare module '@elastic/elasticsearch/api/api/indices.recovery.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.recovery'>;
}
declare module '@elastic/elasticsearch/api/api/indices.refresh.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.refresh'>;
}
declare module '@elastic/elasticsearch/api/api/indices.reload_search_analyzers.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.reload_search_analyzers'>;
}
declare module '@elastic/elasticsearch/api/api/indices.rollover.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.rollover'>;
}
declare module '@elastic/elasticsearch/api/api/indices.segments.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.segments'>;
}
declare module '@elastic/elasticsearch/api/api/indices.shard_stores.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.shard_stores'>;
}
declare module '@elastic/elasticsearch/api/api/indices.shrink.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.shrink'>;
}
declare module '@elastic/elasticsearch/api/api/indices.split.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.split'>;
}
declare module '@elastic/elasticsearch/api/api/indices.stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.stats'>;
}
declare module '@elastic/elasticsearch/api/api/indices.unfreeze.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.unfreeze'>;
}
declare module '@elastic/elasticsearch/api/api/indices.update_aliases.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.update_aliases'>;
}
declare module '@elastic/elasticsearch/api/api/indices.upgrade.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.upgrade'>;
}
declare module '@elastic/elasticsearch/api/api/indices.validate_query.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/indices.validate_query'>;
}
declare module '@elastic/elasticsearch/api/api/info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/info'>;
}
declare module '@elastic/elasticsearch/api/api/ingest.delete_pipeline.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ingest.delete_pipeline'>;
}
declare module '@elastic/elasticsearch/api/api/ingest.get_pipeline.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ingest.get_pipeline'>;
}
declare module '@elastic/elasticsearch/api/api/ingest.processor_grok.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ingest.processor_grok'>;
}
declare module '@elastic/elasticsearch/api/api/ingest.put_pipeline.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ingest.put_pipeline'>;
}
declare module '@elastic/elasticsearch/api/api/ingest.simulate.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ingest.simulate'>;
}
declare module '@elastic/elasticsearch/api/api/license.delete.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.delete'>;
}
declare module '@elastic/elasticsearch/api/api/license.get_basic_status.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.get_basic_status'>;
}
declare module '@elastic/elasticsearch/api/api/license.get_trial_status.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.get_trial_status'>;
}
declare module '@elastic/elasticsearch/api/api/license.get.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.get'>;
}
declare module '@elastic/elasticsearch/api/api/license.post_start_basic.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.post_start_basic'>;
}
declare module '@elastic/elasticsearch/api/api/license.post_start_trial.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.post_start_trial'>;
}
declare module '@elastic/elasticsearch/api/api/license.post.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/license.post'>;
}
declare module '@elastic/elasticsearch/api/api/mget.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/mget'>;
}
declare module '@elastic/elasticsearch/api/api/migration.deprecations.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/migration.deprecations'>;
}
declare module '@elastic/elasticsearch/api/api/ml.close_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.close_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_calendar_event.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_calendar_event'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_calendar_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_calendar_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_calendar.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_calendar'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_data_frame_analytics.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_data_frame_analytics'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_expired_data.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_expired_data'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_filter.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_filter'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_forecast.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_forecast'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.delete_model_snapshot.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.delete_model_snapshot'>;
}
declare module '@elastic/elasticsearch/api/api/ml.evaluate_data_frame.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.evaluate_data_frame'>;
}
declare module '@elastic/elasticsearch/api/api/ml.find_file_structure.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.find_file_structure'>;
}
declare module '@elastic/elasticsearch/api/api/ml.flush_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.flush_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.forecast.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.forecast'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_buckets.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_buckets'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_calendar_events.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_calendar_events'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_calendars.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_calendars'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_categories.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_categories'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_data_frame_analytics_stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_data_frame_analytics_stats'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_data_frame_analytics.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_data_frame_analytics'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_datafeed_stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_datafeed_stats'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_datafeeds.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_datafeeds'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_filters.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_filters'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_influencers.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_influencers'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_job_stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_job_stats'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_jobs.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_jobs'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_model_snapshots.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_model_snapshots'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_overall_buckets.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_overall_buckets'>;
}
declare module '@elastic/elasticsearch/api/api/ml.get_records.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.get_records'>;
}
declare module '@elastic/elasticsearch/api/api/ml.info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.info'>;
}
declare module '@elastic/elasticsearch/api/api/ml.open_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.open_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.post_calendar_events.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.post_calendar_events'>;
}
declare module '@elastic/elasticsearch/api/api/ml.post_data.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.post_data'>;
}
declare module '@elastic/elasticsearch/api/api/ml.preview_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.preview_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_calendar_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_calendar_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_calendar.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_calendar'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_data_frame_analytics.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_data_frame_analytics'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_filter.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_filter'>;
}
declare module '@elastic/elasticsearch/api/api/ml.put_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.put_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.revert_model_snapshot.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.revert_model_snapshot'>;
}
declare module '@elastic/elasticsearch/api/api/ml.set_upgrade_mode.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.set_upgrade_mode'>;
}
declare module '@elastic/elasticsearch/api/api/ml.start_data_frame_analytics.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.start_data_frame_analytics'>;
}
declare module '@elastic/elasticsearch/api/api/ml.start_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.start_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.stop_data_frame_analytics.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.stop_data_frame_analytics'>;
}
declare module '@elastic/elasticsearch/api/api/ml.stop_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.stop_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.update_datafeed.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.update_datafeed'>;
}
declare module '@elastic/elasticsearch/api/api/ml.update_filter.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.update_filter'>;
}
declare module '@elastic/elasticsearch/api/api/ml.update_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.update_job'>;
}
declare module '@elastic/elasticsearch/api/api/ml.update_model_snapshot.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.update_model_snapshot'>;
}
declare module '@elastic/elasticsearch/api/api/ml.validate_detector.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.validate_detector'>;
}
declare module '@elastic/elasticsearch/api/api/ml.validate.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ml.validate'>;
}
declare module '@elastic/elasticsearch/api/api/monitoring.bulk.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/monitoring.bulk'>;
}
declare module '@elastic/elasticsearch/api/api/msearch_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/msearch_template'>;
}
declare module '@elastic/elasticsearch/api/api/msearch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/msearch'>;
}
declare module '@elastic/elasticsearch/api/api/mtermvectors.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/mtermvectors'>;
}
declare module '@elastic/elasticsearch/api/api/nodes.hot_threads.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/nodes.hot_threads'>;
}
declare module '@elastic/elasticsearch/api/api/nodes.info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/nodes.info'>;
}
declare module '@elastic/elasticsearch/api/api/nodes.reload_secure_settings.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/nodes.reload_secure_settings'>;
}
declare module '@elastic/elasticsearch/api/api/nodes.stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/nodes.stats'>;
}
declare module '@elastic/elasticsearch/api/api/nodes.usage.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/nodes.usage'>;
}
declare module '@elastic/elasticsearch/api/api/ping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ping'>;
}
declare module '@elastic/elasticsearch/api/api/put_script.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/put_script'>;
}
declare module '@elastic/elasticsearch/api/api/rank_eval.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rank_eval'>;
}
declare module '@elastic/elasticsearch/api/api/reindex_rethrottle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/reindex_rethrottle'>;
}
declare module '@elastic/elasticsearch/api/api/reindex.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/reindex'>;
}
declare module '@elastic/elasticsearch/api/api/render_search_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/render_search_template'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.delete_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.delete_job'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.get_jobs.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.get_jobs'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.get_rollup_caps.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.get_rollup_caps'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.get_rollup_index_caps.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.get_rollup_index_caps'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.put_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.put_job'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.rollup_search.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.rollup_search'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.start_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.start_job'>;
}
declare module '@elastic/elasticsearch/api/api/rollup.stop_job.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/rollup.stop_job'>;
}
declare module '@elastic/elasticsearch/api/api/scripts_painless_execute.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/scripts_painless_execute'>;
}
declare module '@elastic/elasticsearch/api/api/scroll.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/scroll'>;
}
declare module '@elastic/elasticsearch/api/api/search_shards.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/search_shards'>;
}
declare module '@elastic/elasticsearch/api/api/search_template.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/search_template'>;
}
declare module '@elastic/elasticsearch/api/api/search.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/search'>;
}
declare module '@elastic/elasticsearch/api/api/security.authenticate.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.authenticate'>;
}
declare module '@elastic/elasticsearch/api/api/security.change_password.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.change_password'>;
}
declare module '@elastic/elasticsearch/api/api/security.clear_cached_realms.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.clear_cached_realms'>;
}
declare module '@elastic/elasticsearch/api/api/security.clear_cached_roles.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.clear_cached_roles'>;
}
declare module '@elastic/elasticsearch/api/api/security.create_api_key.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.create_api_key'>;
}
declare module '@elastic/elasticsearch/api/api/security.delete_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.delete_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.delete_role_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.delete_role_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/security.delete_role.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.delete_role'>;
}
declare module '@elastic/elasticsearch/api/api/security.delete_user.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.delete_user'>;
}
declare module '@elastic/elasticsearch/api/api/security.disable_user.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.disable_user'>;
}
declare module '@elastic/elasticsearch/api/api/security.enable_user.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.enable_user'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_api_key.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_api_key'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_builtin_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_builtin_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_role_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_role_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_role.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_role'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_token.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_token'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_user_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_user_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.get_user.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.get_user'>;
}
declare module '@elastic/elasticsearch/api/api/security.has_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.has_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.invalidate_api_key.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.invalidate_api_key'>;
}
declare module '@elastic/elasticsearch/api/api/security.invalidate_token.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.invalidate_token'>;
}
declare module '@elastic/elasticsearch/api/api/security.put_privileges.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.put_privileges'>;
}
declare module '@elastic/elasticsearch/api/api/security.put_role_mapping.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.put_role_mapping'>;
}
declare module '@elastic/elasticsearch/api/api/security.put_role.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.put_role'>;
}
declare module '@elastic/elasticsearch/api/api/security.put_user.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/security.put_user'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.create_repository.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.create_repository'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.create.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.create'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.delete_repository.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.delete_repository'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.delete.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.delete'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.get_repository.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.get_repository'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.get.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.get'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.restore.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.restore'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.status.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.status'>;
}
declare module '@elastic/elasticsearch/api/api/snapshot.verify_repository.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/snapshot.verify_repository'>;
}
declare module '@elastic/elasticsearch/api/api/sql.clear_cursor.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/sql.clear_cursor'>;
}
declare module '@elastic/elasticsearch/api/api/sql.query.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/sql.query'>;
}
declare module '@elastic/elasticsearch/api/api/sql.translate.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/sql.translate'>;
}
declare module '@elastic/elasticsearch/api/api/ssl.certificates.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/ssl.certificates'>;
}
declare module '@elastic/elasticsearch/api/api/tasks.cancel.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/tasks.cancel'>;
}
declare module '@elastic/elasticsearch/api/api/tasks.get.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/tasks.get'>;
}
declare module '@elastic/elasticsearch/api/api/tasks.list.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/tasks.list'>;
}
declare module '@elastic/elasticsearch/api/api/termvectors.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/termvectors'>;
}
declare module '@elastic/elasticsearch/api/api/update_by_query_rethrottle.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/update_by_query_rethrottle'>;
}
declare module '@elastic/elasticsearch/api/api/update_by_query.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/update_by_query'>;
}
declare module '@elastic/elasticsearch/api/api/update.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/update'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.ack_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.ack_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.activate_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.activate_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.deactivate_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.deactivate_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.delete_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.delete_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.execute_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.execute_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.get_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.get_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.put_watch.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.put_watch'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.start.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.start'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.stats.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.stats'>;
}
declare module '@elastic/elasticsearch/api/api/watcher.stop.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/watcher.stop'>;
}
declare module '@elastic/elasticsearch/api/api/xpack.info.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/xpack.info'>;
}
declare module '@elastic/elasticsearch/api/api/xpack.usage.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api/api/xpack.usage'>;
}
declare module '@elastic/elasticsearch/api/index' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api'>;
}
declare module '@elastic/elasticsearch/api/index.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/api'>;
}
declare module '@elastic/elasticsearch/index' {
  declare module.exports: $Exports<'@elastic/elasticsearch'>;
}
declare module '@elastic/elasticsearch/index.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch'>;
}
declare module '@elastic/elasticsearch/lib/Connection.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/Connection'>;
}
declare module '@elastic/elasticsearch/lib/errors.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/errors'>;
}
declare module '@elastic/elasticsearch/lib/pool/BaseConnectionPool.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/pool/BaseConnectionPool'>;
}
declare module '@elastic/elasticsearch/lib/pool/CloudConnectionPool.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/pool/CloudConnectionPool'>;
}
declare module '@elastic/elasticsearch/lib/pool/ConnectionPool.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/pool/ConnectionPool'>;
}
declare module '@elastic/elasticsearch/lib/pool/index' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/pool'>;
}
declare module '@elastic/elasticsearch/lib/pool/index.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/pool'>;
}
declare module '@elastic/elasticsearch/lib/Serializer.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/Serializer'>;
}
declare module '@elastic/elasticsearch/lib/Transport.js' {
  declare module.exports: $Exports<'@elastic/elasticsearch/lib/Transport'>;
}
