// flow-typed signature: 9c527524376089f4f810f31044f80a3e
// flow-typed version: <<STUB>>/base64url_v^3.0.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base64url/dist/base64url' {
  declare module.exports: any;
}

declare module 'base64url/dist/pad-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base64url/dist/base64url.js' {
  declare module.exports: $Exports<'base64url/dist/base64url'>;
}
declare module 'base64url/dist/pad-string.js' {
  declare module.exports: $Exports<'base64url/dist/pad-string'>;
}
declare module 'base64url/index' {
  declare module.exports: $Exports<'base64url'>;
}
declare module 'base64url/index.js' {
  declare module.exports: $Exports<'base64url'>;
}
