// flow-typed signature: 98f8eda5d5c634b6bdc0ac44e7cad423
// flow-typed version: <<STUB>>/bcrypto_v^3.1.5/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcrypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcrypto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcrypto/lib/aead-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/aead' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/aes-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/aes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/bcrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/bcrypto' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2b512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s128' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/blake2s256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/bn-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/bn' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ccmp' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/chacha20-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/chacha20' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cipher-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cipher' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cleanse-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cleanse' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cshake' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cshake128' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/cshake256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/drbg' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/dsa-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/dsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/dsaies' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/eb2k' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ecies' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ed25519-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ed25519' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ed448-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ed448' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/asn1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/openssl' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/pem' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/pemcrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/pkcs1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/pkcs5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/pkcs8' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/rfc3279' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/sec1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/encoding/x509' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/gost94' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/hash160-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/hash160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/hash256-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/hash256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/hkdf' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/asn1-mini' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/base64' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/ciphers' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/curves' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/custom-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/custom' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/dsakey' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/eckey' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/hmac' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/mont' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/objects' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/primes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/rsakey' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/signature' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/internal/util' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/aead' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/aes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/blake2b' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/blake2s' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/bn' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/chacha20' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/cipher' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/aes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/blowfish' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/camellia' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/cast5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/des' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/gcm' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/idea' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/modes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/rc2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ciphers/twofish' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/cleanse' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/curve25519' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/curves' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/dsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ecdsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ed25519' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ed448' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/eddsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/hash160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/hash256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/keccak' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/md4' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/md5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/murmur3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/p192' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/p224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/p256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/p384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/p521' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/pbkdf2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/poly1305' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/random' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/ripemd160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/rsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/schnorr' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/scrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/secp256k1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/sha512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/siphash' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/js/whirlpool' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/keccak512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/kmac' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/kmac128' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/kmac256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md4-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md4' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md5-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/md5sha1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/merkle' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/mrkl' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/murmur3-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/murmur3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/aead' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/aes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/binding' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/blake2b' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/blake2s' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/bn' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/chacha20' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/cipher' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/cleanse' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/dsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/ecdsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/ed25519' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/ed448' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/hash160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/hash256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/keccak' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/md4' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/md5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/murmur3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/p192' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/p224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/p256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/p384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/p521' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/pbkdf2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/poly1305' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/random' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/ripemd160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/rsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/scrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/secp256k1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/sha512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/siphash' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/native/whirlpool' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/aes' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/blake2b' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/blake2s' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/bn' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/cipher' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/cleanse' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/dsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/hash160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/hash256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/md4' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/md5' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/murmur3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/pbkdf2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/random' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/ripemd160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/rsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/scrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/sha512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/siphash' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/node/whirlpool' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p192-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p192' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p224-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p256-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p384-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p521-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/p521' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/pbkdf2-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/pbkdf2' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/pgp' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/poly1305-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/poly1305' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/random-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/random' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/rc4' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ripemd160-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ripemd160' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/rsa-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/rsa' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/rsaies' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/safe-equal' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/safe' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/scrypt-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/scrypt' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/secp256k1-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/secp256k1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha1-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha1' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha224-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha256-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3-224' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3-256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3-384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3-512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha3' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha384-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha384' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha512-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/sha512' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/shake' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/shake128' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/shake256' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/siphash-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/siphash' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/ssh' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/whirlpool-browser' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/whirlpool' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/x25519' {
  declare module.exports: any;
}

declare module 'bcrypto/lib/x448' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcrypto/lib/aead-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/aead-browser'>;
}
declare module 'bcrypto/lib/aead.js' {
  declare module.exports: $Exports<'bcrypto/lib/aead'>;
}
declare module 'bcrypto/lib/aes-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/aes-browser'>;
}
declare module 'bcrypto/lib/aes.js' {
  declare module.exports: $Exports<'bcrypto/lib/aes'>;
}
declare module 'bcrypto/lib/bcrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/bcrypt'>;
}
declare module 'bcrypto/lib/bcrypto.js' {
  declare module.exports: $Exports<'bcrypto/lib/bcrypto'>;
}
declare module 'bcrypto/lib/blake2b-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b-browser'>;
}
declare module 'bcrypto/lib/blake2b.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b'>;
}
declare module 'bcrypto/lib/blake2b160.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b160'>;
}
declare module 'bcrypto/lib/blake2b256.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b256'>;
}
declare module 'bcrypto/lib/blake2b384.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b384'>;
}
declare module 'bcrypto/lib/blake2b512.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2b512'>;
}
declare module 'bcrypto/lib/blake2s-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s-browser'>;
}
declare module 'bcrypto/lib/blake2s.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s'>;
}
declare module 'bcrypto/lib/blake2s128.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s128'>;
}
declare module 'bcrypto/lib/blake2s160.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s160'>;
}
declare module 'bcrypto/lib/blake2s224.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s224'>;
}
declare module 'bcrypto/lib/blake2s256.js' {
  declare module.exports: $Exports<'bcrypto/lib/blake2s256'>;
}
declare module 'bcrypto/lib/bn-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/bn-browser'>;
}
declare module 'bcrypto/lib/bn.js' {
  declare module.exports: $Exports<'bcrypto/lib/bn'>;
}
declare module 'bcrypto/lib/ccmp.js' {
  declare module.exports: $Exports<'bcrypto/lib/ccmp'>;
}
declare module 'bcrypto/lib/chacha20-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/chacha20-browser'>;
}
declare module 'bcrypto/lib/chacha20.js' {
  declare module.exports: $Exports<'bcrypto/lib/chacha20'>;
}
declare module 'bcrypto/lib/cipher-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/cipher-browser'>;
}
declare module 'bcrypto/lib/cipher.js' {
  declare module.exports: $Exports<'bcrypto/lib/cipher'>;
}
declare module 'bcrypto/lib/cleanse-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/cleanse-browser'>;
}
declare module 'bcrypto/lib/cleanse.js' {
  declare module.exports: $Exports<'bcrypto/lib/cleanse'>;
}
declare module 'bcrypto/lib/cshake.js' {
  declare module.exports: $Exports<'bcrypto/lib/cshake'>;
}
declare module 'bcrypto/lib/cshake128.js' {
  declare module.exports: $Exports<'bcrypto/lib/cshake128'>;
}
declare module 'bcrypto/lib/cshake256.js' {
  declare module.exports: $Exports<'bcrypto/lib/cshake256'>;
}
declare module 'bcrypto/lib/drbg.js' {
  declare module.exports: $Exports<'bcrypto/lib/drbg'>;
}
declare module 'bcrypto/lib/dsa-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/dsa-browser'>;
}
declare module 'bcrypto/lib/dsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/dsa'>;
}
declare module 'bcrypto/lib/dsaies.js' {
  declare module.exports: $Exports<'bcrypto/lib/dsaies'>;
}
declare module 'bcrypto/lib/eb2k.js' {
  declare module.exports: $Exports<'bcrypto/lib/eb2k'>;
}
declare module 'bcrypto/lib/ecies.js' {
  declare module.exports: $Exports<'bcrypto/lib/ecies'>;
}
declare module 'bcrypto/lib/ed25519-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/ed25519-browser'>;
}
declare module 'bcrypto/lib/ed25519.js' {
  declare module.exports: $Exports<'bcrypto/lib/ed25519'>;
}
declare module 'bcrypto/lib/ed448-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/ed448-browser'>;
}
declare module 'bcrypto/lib/ed448.js' {
  declare module.exports: $Exports<'bcrypto/lib/ed448'>;
}
declare module 'bcrypto/lib/encoding/asn1.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/asn1'>;
}
declare module 'bcrypto/lib/encoding/index' {
  declare module.exports: $Exports<'bcrypto/lib/encoding'>;
}
declare module 'bcrypto/lib/encoding/index.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding'>;
}
declare module 'bcrypto/lib/encoding/openssl.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/openssl'>;
}
declare module 'bcrypto/lib/encoding/pem.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/pem'>;
}
declare module 'bcrypto/lib/encoding/pemcrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/pemcrypt'>;
}
declare module 'bcrypto/lib/encoding/pkcs1.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/pkcs1'>;
}
declare module 'bcrypto/lib/encoding/pkcs5.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/pkcs5'>;
}
declare module 'bcrypto/lib/encoding/pkcs8.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/pkcs8'>;
}
declare module 'bcrypto/lib/encoding/rfc3279.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/rfc3279'>;
}
declare module 'bcrypto/lib/encoding/sec1.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/sec1'>;
}
declare module 'bcrypto/lib/encoding/x509.js' {
  declare module.exports: $Exports<'bcrypto/lib/encoding/x509'>;
}
declare module 'bcrypto/lib/gost94.js' {
  declare module.exports: $Exports<'bcrypto/lib/gost94'>;
}
declare module 'bcrypto/lib/hash160-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/hash160-browser'>;
}
declare module 'bcrypto/lib/hash160.js' {
  declare module.exports: $Exports<'bcrypto/lib/hash160'>;
}
declare module 'bcrypto/lib/hash256-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/hash256-browser'>;
}
declare module 'bcrypto/lib/hash256.js' {
  declare module.exports: $Exports<'bcrypto/lib/hash256'>;
}
declare module 'bcrypto/lib/hkdf.js' {
  declare module.exports: $Exports<'bcrypto/lib/hkdf'>;
}
declare module 'bcrypto/lib/internal/asn1-mini.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/asn1-mini'>;
}
declare module 'bcrypto/lib/internal/base64.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/base64'>;
}
declare module 'bcrypto/lib/internal/ciphers.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/ciphers'>;
}
declare module 'bcrypto/lib/internal/curves.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/curves'>;
}
declare module 'bcrypto/lib/internal/custom-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/custom-browser'>;
}
declare module 'bcrypto/lib/internal/custom.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/custom'>;
}
declare module 'bcrypto/lib/internal/dsakey.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/dsakey'>;
}
declare module 'bcrypto/lib/internal/eckey.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/eckey'>;
}
declare module 'bcrypto/lib/internal/hmac.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/hmac'>;
}
declare module 'bcrypto/lib/internal/mont.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/mont'>;
}
declare module 'bcrypto/lib/internal/objects.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/objects'>;
}
declare module 'bcrypto/lib/internal/primes.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/primes'>;
}
declare module 'bcrypto/lib/internal/rsakey.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/rsakey'>;
}
declare module 'bcrypto/lib/internal/signature.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/signature'>;
}
declare module 'bcrypto/lib/internal/util.js' {
  declare module.exports: $Exports<'bcrypto/lib/internal/util'>;
}
declare module 'bcrypto/lib/js/aead.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/aead'>;
}
declare module 'bcrypto/lib/js/aes.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/aes'>;
}
declare module 'bcrypto/lib/js/blake2b.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/blake2b'>;
}
declare module 'bcrypto/lib/js/blake2s.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/blake2s'>;
}
declare module 'bcrypto/lib/js/bn.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/bn'>;
}
declare module 'bcrypto/lib/js/chacha20.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/chacha20'>;
}
declare module 'bcrypto/lib/js/cipher.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/cipher'>;
}
declare module 'bcrypto/lib/js/ciphers/aes.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/aes'>;
}
declare module 'bcrypto/lib/js/ciphers/blowfish.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/blowfish'>;
}
declare module 'bcrypto/lib/js/ciphers/camellia.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/camellia'>;
}
declare module 'bcrypto/lib/js/ciphers/cast5.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/cast5'>;
}
declare module 'bcrypto/lib/js/ciphers/des.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/des'>;
}
declare module 'bcrypto/lib/js/ciphers/gcm.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/gcm'>;
}
declare module 'bcrypto/lib/js/ciphers/idea.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/idea'>;
}
declare module 'bcrypto/lib/js/ciphers/modes.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/modes'>;
}
declare module 'bcrypto/lib/js/ciphers/rc2.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/rc2'>;
}
declare module 'bcrypto/lib/js/ciphers/twofish.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ciphers/twofish'>;
}
declare module 'bcrypto/lib/js/cleanse.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/cleanse'>;
}
declare module 'bcrypto/lib/js/curve25519.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/curve25519'>;
}
declare module 'bcrypto/lib/js/curves.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/curves'>;
}
declare module 'bcrypto/lib/js/dsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/dsa'>;
}
declare module 'bcrypto/lib/js/ecdsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ecdsa'>;
}
declare module 'bcrypto/lib/js/ed25519.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ed25519'>;
}
declare module 'bcrypto/lib/js/ed448.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ed448'>;
}
declare module 'bcrypto/lib/js/eddsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/eddsa'>;
}
declare module 'bcrypto/lib/js/hash160.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/hash160'>;
}
declare module 'bcrypto/lib/js/hash256.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/hash256'>;
}
declare module 'bcrypto/lib/js/keccak.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/keccak'>;
}
declare module 'bcrypto/lib/js/md4.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/md4'>;
}
declare module 'bcrypto/lib/js/md5.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/md5'>;
}
declare module 'bcrypto/lib/js/murmur3.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/murmur3'>;
}
declare module 'bcrypto/lib/js/p192.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/p192'>;
}
declare module 'bcrypto/lib/js/p224.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/p224'>;
}
declare module 'bcrypto/lib/js/p256.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/p256'>;
}
declare module 'bcrypto/lib/js/p384.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/p384'>;
}
declare module 'bcrypto/lib/js/p521.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/p521'>;
}
declare module 'bcrypto/lib/js/pbkdf2.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/pbkdf2'>;
}
declare module 'bcrypto/lib/js/poly1305.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/poly1305'>;
}
declare module 'bcrypto/lib/js/random.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/random'>;
}
declare module 'bcrypto/lib/js/ripemd160.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/ripemd160'>;
}
declare module 'bcrypto/lib/js/rsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/rsa'>;
}
declare module 'bcrypto/lib/js/schnorr.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/schnorr'>;
}
declare module 'bcrypto/lib/js/scrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/scrypt'>;
}
declare module 'bcrypto/lib/js/secp256k1.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/secp256k1'>;
}
declare module 'bcrypto/lib/js/sha1.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha1'>;
}
declare module 'bcrypto/lib/js/sha224.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha224'>;
}
declare module 'bcrypto/lib/js/sha256.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha256'>;
}
declare module 'bcrypto/lib/js/sha3.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha3'>;
}
declare module 'bcrypto/lib/js/sha384.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha384'>;
}
declare module 'bcrypto/lib/js/sha512.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/sha512'>;
}
declare module 'bcrypto/lib/js/siphash.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/siphash'>;
}
declare module 'bcrypto/lib/js/whirlpool.js' {
  declare module.exports: $Exports<'bcrypto/lib/js/whirlpool'>;
}
declare module 'bcrypto/lib/keccak-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak-browser'>;
}
declare module 'bcrypto/lib/keccak.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak'>;
}
declare module 'bcrypto/lib/keccak224.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak224'>;
}
declare module 'bcrypto/lib/keccak256.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak256'>;
}
declare module 'bcrypto/lib/keccak384.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak384'>;
}
declare module 'bcrypto/lib/keccak512.js' {
  declare module.exports: $Exports<'bcrypto/lib/keccak512'>;
}
declare module 'bcrypto/lib/kmac.js' {
  declare module.exports: $Exports<'bcrypto/lib/kmac'>;
}
declare module 'bcrypto/lib/kmac128.js' {
  declare module.exports: $Exports<'bcrypto/lib/kmac128'>;
}
declare module 'bcrypto/lib/kmac256.js' {
  declare module.exports: $Exports<'bcrypto/lib/kmac256'>;
}
declare module 'bcrypto/lib/md2.js' {
  declare module.exports: $Exports<'bcrypto/lib/md2'>;
}
declare module 'bcrypto/lib/md4-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/md4-browser'>;
}
declare module 'bcrypto/lib/md4.js' {
  declare module.exports: $Exports<'bcrypto/lib/md4'>;
}
declare module 'bcrypto/lib/md5-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/md5-browser'>;
}
declare module 'bcrypto/lib/md5.js' {
  declare module.exports: $Exports<'bcrypto/lib/md5'>;
}
declare module 'bcrypto/lib/md5sha1.js' {
  declare module.exports: $Exports<'bcrypto/lib/md5sha1'>;
}
declare module 'bcrypto/lib/merkle.js' {
  declare module.exports: $Exports<'bcrypto/lib/merkle'>;
}
declare module 'bcrypto/lib/mrkl.js' {
  declare module.exports: $Exports<'bcrypto/lib/mrkl'>;
}
declare module 'bcrypto/lib/murmur3-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/murmur3-browser'>;
}
declare module 'bcrypto/lib/murmur3.js' {
  declare module.exports: $Exports<'bcrypto/lib/murmur3'>;
}
declare module 'bcrypto/lib/native/aead.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/aead'>;
}
declare module 'bcrypto/lib/native/aes.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/aes'>;
}
declare module 'bcrypto/lib/native/binding.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/binding'>;
}
declare module 'bcrypto/lib/native/blake2b.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/blake2b'>;
}
declare module 'bcrypto/lib/native/blake2s.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/blake2s'>;
}
declare module 'bcrypto/lib/native/bn.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/bn'>;
}
declare module 'bcrypto/lib/native/chacha20.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/chacha20'>;
}
declare module 'bcrypto/lib/native/cipher.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/cipher'>;
}
declare module 'bcrypto/lib/native/cleanse.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/cleanse'>;
}
declare module 'bcrypto/lib/native/dsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/dsa'>;
}
declare module 'bcrypto/lib/native/ecdsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/ecdsa'>;
}
declare module 'bcrypto/lib/native/ed25519.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/ed25519'>;
}
declare module 'bcrypto/lib/native/ed448.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/ed448'>;
}
declare module 'bcrypto/lib/native/hash160.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/hash160'>;
}
declare module 'bcrypto/lib/native/hash256.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/hash256'>;
}
declare module 'bcrypto/lib/native/keccak.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/keccak'>;
}
declare module 'bcrypto/lib/native/md4.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/md4'>;
}
declare module 'bcrypto/lib/native/md5.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/md5'>;
}
declare module 'bcrypto/lib/native/murmur3.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/murmur3'>;
}
declare module 'bcrypto/lib/native/p192.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/p192'>;
}
declare module 'bcrypto/lib/native/p224.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/p224'>;
}
declare module 'bcrypto/lib/native/p256.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/p256'>;
}
declare module 'bcrypto/lib/native/p384.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/p384'>;
}
declare module 'bcrypto/lib/native/p521.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/p521'>;
}
declare module 'bcrypto/lib/native/pbkdf2.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/pbkdf2'>;
}
declare module 'bcrypto/lib/native/poly1305.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/poly1305'>;
}
declare module 'bcrypto/lib/native/random.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/random'>;
}
declare module 'bcrypto/lib/native/ripemd160.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/ripemd160'>;
}
declare module 'bcrypto/lib/native/rsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/rsa'>;
}
declare module 'bcrypto/lib/native/scrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/scrypt'>;
}
declare module 'bcrypto/lib/native/secp256k1.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/secp256k1'>;
}
declare module 'bcrypto/lib/native/sha1.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha1'>;
}
declare module 'bcrypto/lib/native/sha224.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha224'>;
}
declare module 'bcrypto/lib/native/sha256.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha256'>;
}
declare module 'bcrypto/lib/native/sha3.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha3'>;
}
declare module 'bcrypto/lib/native/sha384.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha384'>;
}
declare module 'bcrypto/lib/native/sha512.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/sha512'>;
}
declare module 'bcrypto/lib/native/siphash.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/siphash'>;
}
declare module 'bcrypto/lib/native/whirlpool.js' {
  declare module.exports: $Exports<'bcrypto/lib/native/whirlpool'>;
}
declare module 'bcrypto/lib/node/aes.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/aes'>;
}
declare module 'bcrypto/lib/node/blake2b.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/blake2b'>;
}
declare module 'bcrypto/lib/node/blake2s.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/blake2s'>;
}
declare module 'bcrypto/lib/node/bn.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/bn'>;
}
declare module 'bcrypto/lib/node/cipher.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/cipher'>;
}
declare module 'bcrypto/lib/node/cleanse.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/cleanse'>;
}
declare module 'bcrypto/lib/node/dsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/dsa'>;
}
declare module 'bcrypto/lib/node/hash160.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/hash160'>;
}
declare module 'bcrypto/lib/node/hash256.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/hash256'>;
}
declare module 'bcrypto/lib/node/md4.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/md4'>;
}
declare module 'bcrypto/lib/node/md5.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/md5'>;
}
declare module 'bcrypto/lib/node/murmur3.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/murmur3'>;
}
declare module 'bcrypto/lib/node/pbkdf2.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/pbkdf2'>;
}
declare module 'bcrypto/lib/node/random.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/random'>;
}
declare module 'bcrypto/lib/node/ripemd160.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/ripemd160'>;
}
declare module 'bcrypto/lib/node/rsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/rsa'>;
}
declare module 'bcrypto/lib/node/scrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/scrypt'>;
}
declare module 'bcrypto/lib/node/sha1.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha1'>;
}
declare module 'bcrypto/lib/node/sha224.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha224'>;
}
declare module 'bcrypto/lib/node/sha256.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha256'>;
}
declare module 'bcrypto/lib/node/sha3.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha3'>;
}
declare module 'bcrypto/lib/node/sha384.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha384'>;
}
declare module 'bcrypto/lib/node/sha512.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/sha512'>;
}
declare module 'bcrypto/lib/node/siphash.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/siphash'>;
}
declare module 'bcrypto/lib/node/whirlpool.js' {
  declare module.exports: $Exports<'bcrypto/lib/node/whirlpool'>;
}
declare module 'bcrypto/lib/p192-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/p192-browser'>;
}
declare module 'bcrypto/lib/p192.js' {
  declare module.exports: $Exports<'bcrypto/lib/p192'>;
}
declare module 'bcrypto/lib/p224-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/p224-browser'>;
}
declare module 'bcrypto/lib/p224.js' {
  declare module.exports: $Exports<'bcrypto/lib/p224'>;
}
declare module 'bcrypto/lib/p256-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/p256-browser'>;
}
declare module 'bcrypto/lib/p256.js' {
  declare module.exports: $Exports<'bcrypto/lib/p256'>;
}
declare module 'bcrypto/lib/p384-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/p384-browser'>;
}
declare module 'bcrypto/lib/p384.js' {
  declare module.exports: $Exports<'bcrypto/lib/p384'>;
}
declare module 'bcrypto/lib/p521-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/p521-browser'>;
}
declare module 'bcrypto/lib/p521.js' {
  declare module.exports: $Exports<'bcrypto/lib/p521'>;
}
declare module 'bcrypto/lib/pbkdf2-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/pbkdf2-browser'>;
}
declare module 'bcrypto/lib/pbkdf2.js' {
  declare module.exports: $Exports<'bcrypto/lib/pbkdf2'>;
}
declare module 'bcrypto/lib/pgp.js' {
  declare module.exports: $Exports<'bcrypto/lib/pgp'>;
}
declare module 'bcrypto/lib/poly1305-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/poly1305-browser'>;
}
declare module 'bcrypto/lib/poly1305.js' {
  declare module.exports: $Exports<'bcrypto/lib/poly1305'>;
}
declare module 'bcrypto/lib/random-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/random-browser'>;
}
declare module 'bcrypto/lib/random.js' {
  declare module.exports: $Exports<'bcrypto/lib/random'>;
}
declare module 'bcrypto/lib/rc4.js' {
  declare module.exports: $Exports<'bcrypto/lib/rc4'>;
}
declare module 'bcrypto/lib/ripemd160-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/ripemd160-browser'>;
}
declare module 'bcrypto/lib/ripemd160.js' {
  declare module.exports: $Exports<'bcrypto/lib/ripemd160'>;
}
declare module 'bcrypto/lib/rsa-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/rsa-browser'>;
}
declare module 'bcrypto/lib/rsa.js' {
  declare module.exports: $Exports<'bcrypto/lib/rsa'>;
}
declare module 'bcrypto/lib/rsaies.js' {
  declare module.exports: $Exports<'bcrypto/lib/rsaies'>;
}
declare module 'bcrypto/lib/safe-equal.js' {
  declare module.exports: $Exports<'bcrypto/lib/safe-equal'>;
}
declare module 'bcrypto/lib/safe.js' {
  declare module.exports: $Exports<'bcrypto/lib/safe'>;
}
declare module 'bcrypto/lib/scrypt-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/scrypt-browser'>;
}
declare module 'bcrypto/lib/scrypt.js' {
  declare module.exports: $Exports<'bcrypto/lib/scrypt'>;
}
declare module 'bcrypto/lib/secp256k1-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/secp256k1-browser'>;
}
declare module 'bcrypto/lib/secp256k1.js' {
  declare module.exports: $Exports<'bcrypto/lib/secp256k1'>;
}
declare module 'bcrypto/lib/sha1-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha1-browser'>;
}
declare module 'bcrypto/lib/sha1.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha1'>;
}
declare module 'bcrypto/lib/sha224-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha224-browser'>;
}
declare module 'bcrypto/lib/sha224.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha224'>;
}
declare module 'bcrypto/lib/sha256-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha256-browser'>;
}
declare module 'bcrypto/lib/sha256.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha256'>;
}
declare module 'bcrypto/lib/sha3-224.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3-224'>;
}
declare module 'bcrypto/lib/sha3-256.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3-256'>;
}
declare module 'bcrypto/lib/sha3-384.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3-384'>;
}
declare module 'bcrypto/lib/sha3-512.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3-512'>;
}
declare module 'bcrypto/lib/sha3-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3-browser'>;
}
declare module 'bcrypto/lib/sha3.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha3'>;
}
declare module 'bcrypto/lib/sha384-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha384-browser'>;
}
declare module 'bcrypto/lib/sha384.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha384'>;
}
declare module 'bcrypto/lib/sha512-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha512-browser'>;
}
declare module 'bcrypto/lib/sha512.js' {
  declare module.exports: $Exports<'bcrypto/lib/sha512'>;
}
declare module 'bcrypto/lib/shake.js' {
  declare module.exports: $Exports<'bcrypto/lib/shake'>;
}
declare module 'bcrypto/lib/shake128.js' {
  declare module.exports: $Exports<'bcrypto/lib/shake128'>;
}
declare module 'bcrypto/lib/shake256.js' {
  declare module.exports: $Exports<'bcrypto/lib/shake256'>;
}
declare module 'bcrypto/lib/siphash-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/siphash-browser'>;
}
declare module 'bcrypto/lib/siphash.js' {
  declare module.exports: $Exports<'bcrypto/lib/siphash'>;
}
declare module 'bcrypto/lib/ssh.js' {
  declare module.exports: $Exports<'bcrypto/lib/ssh'>;
}
declare module 'bcrypto/lib/whirlpool-browser.js' {
  declare module.exports: $Exports<'bcrypto/lib/whirlpool-browser'>;
}
declare module 'bcrypto/lib/whirlpool.js' {
  declare module.exports: $Exports<'bcrypto/lib/whirlpool'>;
}
declare module 'bcrypto/lib/x25519.js' {
  declare module.exports: $Exports<'bcrypto/lib/x25519'>;
}
declare module 'bcrypto/lib/x448.js' {
  declare module.exports: $Exports<'bcrypto/lib/x448'>;
}
