// flow-typed signature: 4729bf3b2dac8c5d3f9539ebb858b48c
// flow-typed version: <<STUB>>/borc_v2.1.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'borc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'borc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'borc/benchmarks' {
  declare module.exports: any;
}

declare module 'borc/dist' {
  declare module.exports: any;
}

declare module 'borc/dist/index.min' {
  declare module.exports: any;
}

declare module 'borc/src/commented' {
  declare module.exports: any;
}

declare module 'borc/src/constants' {
  declare module.exports: any;
}

declare module 'borc/src/decoder.asm' {
  declare module.exports: any;
}

declare module 'borc/src/decoder' {
  declare module.exports: any;
}

declare module 'borc/src/diagnose' {
  declare module.exports: any;
}

declare module 'borc/src/encoder' {
  declare module.exports: any;
}

declare module 'borc/src' {
  declare module.exports: any;
}

declare module 'borc/src/simple' {
  declare module.exports: any;
}

declare module 'borc/src/tagged' {
  declare module.exports: any;
}

declare module 'borc/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'borc/benchmarks/index' {
  declare module.exports: $Exports<'borc/benchmarks'>;
}
declare module 'borc/benchmarks/index.js' {
  declare module.exports: $Exports<'borc/benchmarks'>;
}
declare module 'borc/dist/index' {
  declare module.exports: $Exports<'borc/dist'>;
}
declare module 'borc/dist/index.js' {
  declare module.exports: $Exports<'borc/dist'>;
}
declare module 'borc/dist/index.min.js' {
  declare module.exports: $Exports<'borc/dist/index.min'>;
}
declare module 'borc/src/commented.js' {
  declare module.exports: $Exports<'borc/src/commented'>;
}
declare module 'borc/src/constants.js' {
  declare module.exports: $Exports<'borc/src/constants'>;
}
declare module 'borc/src/decoder.asm.js' {
  declare module.exports: $Exports<'borc/src/decoder.asm'>;
}
declare module 'borc/src/decoder.js' {
  declare module.exports: $Exports<'borc/src/decoder'>;
}
declare module 'borc/src/diagnose.js' {
  declare module.exports: $Exports<'borc/src/diagnose'>;
}
declare module 'borc/src/encoder.js' {
  declare module.exports: $Exports<'borc/src/encoder'>;
}
declare module 'borc/src/index' {
  declare module.exports: $Exports<'borc/src'>;
}
declare module 'borc/src/index.js' {
  declare module.exports: $Exports<'borc/src'>;
}
declare module 'borc/src/simple.js' {
  declare module.exports: $Exports<'borc/src/simple'>;
}
declare module 'borc/src/tagged.js' {
  declare module.exports: $Exports<'borc/src/tagged'>;
}
declare module 'borc/src/utils.js' {
  declare module.exports: $Exports<'borc/src/utils'>;
}
