// flow-typed signature: e5bea29128c017b4acd38a9874227d7f
// flow-typed version: <<STUB>>/cardano-wallet_v^0.3.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cardano-wallet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cardano-wallet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cardano-wallet/cardano_wallet_bg' {
  declare module.exports: any;
}

declare module 'cardano-wallet/cardano_wallet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cardano-wallet/cardano_wallet_bg.js' {
  declare module.exports: $Exports<'cardano-wallet/cardano_wallet_bg'>;
}
declare module 'cardano-wallet/cardano_wallet.js' {
  declare module.exports: $Exports<'cardano-wallet/cardano_wallet'>;
}
