// flow-typed signature: 65a6e946503ee63e69e49139d9ea04b5
// flow-typed version: <<STUB>>/cbor_v4.2.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cbor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cbor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cbor/lib/cbor' {
  declare module.exports: any;
}

declare module 'cbor/lib/commented' {
  declare module.exports: any;
}

declare module 'cbor/lib/constants' {
  declare module.exports: any;
}

declare module 'cbor/lib/decoder' {
  declare module.exports: any;
}

declare module 'cbor/lib/diagnose' {
  declare module.exports: any;
}

declare module 'cbor/lib/encoder' {
  declare module.exports: any;
}

declare module 'cbor/lib/map' {
  declare module.exports: any;
}

declare module 'cbor/lib/simple' {
  declare module.exports: any;
}

declare module 'cbor/lib/tagged' {
  declare module.exports: any;
}

declare module 'cbor/lib/utils' {
  declare module.exports: any;
}

declare module 'cbor/vendor/binary-parse-stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cbor/lib/cbor.js' {
  declare module.exports: $Exports<'cbor/lib/cbor'>;
}
declare module 'cbor/lib/commented.js' {
  declare module.exports: $Exports<'cbor/lib/commented'>;
}
declare module 'cbor/lib/constants.js' {
  declare module.exports: $Exports<'cbor/lib/constants'>;
}
declare module 'cbor/lib/decoder.js' {
  declare module.exports: $Exports<'cbor/lib/decoder'>;
}
declare module 'cbor/lib/diagnose.js' {
  declare module.exports: $Exports<'cbor/lib/diagnose'>;
}
declare module 'cbor/lib/encoder.js' {
  declare module.exports: $Exports<'cbor/lib/encoder'>;
}
declare module 'cbor/lib/map.js' {
  declare module.exports: $Exports<'cbor/lib/map'>;
}
declare module 'cbor/lib/simple.js' {
  declare module.exports: $Exports<'cbor/lib/simple'>;
}
declare module 'cbor/lib/tagged.js' {
  declare module.exports: $Exports<'cbor/lib/tagged'>;
}
declare module 'cbor/lib/utils.js' {
  declare module.exports: $Exports<'cbor/lib/utils'>;
}
declare module 'cbor/vendor/binary-parse-stream/index' {
  declare module.exports: $Exports<'cbor/vendor/binary-parse-stream'>;
}
declare module 'cbor/vendor/binary-parse-stream/index.js' {
  declare module.exports: $Exports<'cbor/vendor/binary-parse-stream'>;
}
