// flow-typed signature: 6b2aff3c9585dfbe04a366fb4015a338
// flow-typed version: <<STUB>>/inversify-config-injection_v^0.0.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inversify-config-injection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inversify-config-injection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inversify-config-injection/dist/eager-binder' {
  declare module.exports: any;
}

declare module 'inversify-config-injection/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inversify-config-injection/dist/eager-binder.js' {
  declare module.exports: $Exports<'inversify-config-injection/dist/eager-binder'>;
}
declare module 'inversify-config-injection/dist/index' {
  declare module.exports: $Exports<'inversify-config-injection/dist'>;
}
declare module 'inversify-config-injection/dist/index.js' {
  declare module.exports: $Exports<'inversify-config-injection/dist'>;
}
