// flow-typed signature: d0005f2157aa926d4541790a945858f5
// flow-typed version: <<STUB>>/inversify-vanillajs-helpers_v^2.0.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inversify-vanillajs-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inversify-vanillajs-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inversify-vanillajs-helpers/es/annotate' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/es' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/es/interfaces' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/es/register' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/lib/annotate' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/lib' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/lib/interfaces' {
  declare module.exports: any;
}

declare module 'inversify-vanillajs-helpers/lib/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inversify-vanillajs-helpers/es/annotate.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/es/annotate'>;
}
declare module 'inversify-vanillajs-helpers/es/index' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/es'>;
}
declare module 'inversify-vanillajs-helpers/es/index.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/es'>;
}
declare module 'inversify-vanillajs-helpers/es/interfaces.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/es/interfaces'>;
}
declare module 'inversify-vanillajs-helpers/es/register.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/es/register'>;
}
declare module 'inversify-vanillajs-helpers/lib/annotate.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/lib/annotate'>;
}
declare module 'inversify-vanillajs-helpers/lib/index' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/lib'>;
}
declare module 'inversify-vanillajs-helpers/lib/index.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/lib'>;
}
declare module 'inversify-vanillajs-helpers/lib/interfaces.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/lib/interfaces'>;
}
declare module 'inversify-vanillajs-helpers/lib/register.js' {
  declare module.exports: $Exports<'inversify-vanillajs-helpers/lib/register'>;
}
