// flow-typed signature: 5406531758972ab972c4647ed02c3c36
// flow-typed version: <<STUB>>/js-chain-libs_vfile:js-chain-libs/pkg/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-chain-libs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-chain-libs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-chain-libs/js_chain_libs_bg' {
  declare module.exports: any;
}

declare module 'js-chain-libs/js_chain_libs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-chain-libs/js_chain_libs_bg.js' {
  declare module.exports: $Exports<'js-chain-libs/js_chain_libs_bg'>;
}
declare module 'js-chain-libs/js_chain_libs.js' {
  declare module.exports: $Exports<'js-chain-libs/js_chain_libs'>;
}
