// flow-typed signature: 70d9185e287b822ccd215eff31a5e567
// flow-typed version: <<STUB>>/node-pg-migrate_v^3.16.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-pg-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-pg-migrate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-pg-migrate/dist/db' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/migration-builder' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/migration-template' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/migration' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/domains' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/extensions' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/functions' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/indexes' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/operators' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/other' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/policies' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/roles' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/schemas' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/sequences' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/tables' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/triggers' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/types' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/views' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/operations/viewsMaterialized' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/runner' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/dist/utils' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/db' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/migration-builder' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/migration-template' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/migration' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/domains' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/extensions' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/functions' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/indexes' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/operators' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/other' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/policies' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/roles' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/schemas' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/sequences' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/tables' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/triggers' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/types' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/views' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/operations/viewsMaterialized' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/runner' {
  declare module.exports: any;
}

declare module 'node-pg-migrate/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-pg-migrate/dist/db.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/db'>;
}
declare module 'node-pg-migrate/dist/migration-builder.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/migration-builder'>;
}
declare module 'node-pg-migrate/dist/migration-template.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/migration-template'>;
}
declare module 'node-pg-migrate/dist/migration.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/migration'>;
}
declare module 'node-pg-migrate/dist/operations/domains.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/domains'>;
}
declare module 'node-pg-migrate/dist/operations/extensions.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/extensions'>;
}
declare module 'node-pg-migrate/dist/operations/functions.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/functions'>;
}
declare module 'node-pg-migrate/dist/operations/indexes.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/indexes'>;
}
declare module 'node-pg-migrate/dist/operations/operators.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/operators'>;
}
declare module 'node-pg-migrate/dist/operations/other.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/other'>;
}
declare module 'node-pg-migrate/dist/operations/policies.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/policies'>;
}
declare module 'node-pg-migrate/dist/operations/roles.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/roles'>;
}
declare module 'node-pg-migrate/dist/operations/schemas.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/schemas'>;
}
declare module 'node-pg-migrate/dist/operations/sequences.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/sequences'>;
}
declare module 'node-pg-migrate/dist/operations/tables.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/tables'>;
}
declare module 'node-pg-migrate/dist/operations/triggers.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/triggers'>;
}
declare module 'node-pg-migrate/dist/operations/types.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/types'>;
}
declare module 'node-pg-migrate/dist/operations/views.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/views'>;
}
declare module 'node-pg-migrate/dist/operations/viewsMaterialized.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/operations/viewsMaterialized'>;
}
declare module 'node-pg-migrate/dist/runner.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/runner'>;
}
declare module 'node-pg-migrate/dist/utils.js' {
  declare module.exports: $Exports<'node-pg-migrate/dist/utils'>;
}
declare module 'node-pg-migrate/index' {
  declare module.exports: $Exports<'node-pg-migrate'>;
}
declare module 'node-pg-migrate/index.js' {
  declare module.exports: $Exports<'node-pg-migrate'>;
}
declare module 'node-pg-migrate/lib/db.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/db'>;
}
declare module 'node-pg-migrate/lib/migration-builder.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/migration-builder'>;
}
declare module 'node-pg-migrate/lib/migration-template.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/migration-template'>;
}
declare module 'node-pg-migrate/lib/migration.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/migration'>;
}
declare module 'node-pg-migrate/lib/operations/domains.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/domains'>;
}
declare module 'node-pg-migrate/lib/operations/extensions.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/extensions'>;
}
declare module 'node-pg-migrate/lib/operations/functions.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/functions'>;
}
declare module 'node-pg-migrate/lib/operations/indexes.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/indexes'>;
}
declare module 'node-pg-migrate/lib/operations/operators.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/operators'>;
}
declare module 'node-pg-migrate/lib/operations/other.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/other'>;
}
declare module 'node-pg-migrate/lib/operations/policies.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/policies'>;
}
declare module 'node-pg-migrate/lib/operations/roles.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/roles'>;
}
declare module 'node-pg-migrate/lib/operations/schemas.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/schemas'>;
}
declare module 'node-pg-migrate/lib/operations/sequences.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/sequences'>;
}
declare module 'node-pg-migrate/lib/operations/tables.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/tables'>;
}
declare module 'node-pg-migrate/lib/operations/triggers.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/triggers'>;
}
declare module 'node-pg-migrate/lib/operations/types.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/types'>;
}
declare module 'node-pg-migrate/lib/operations/views.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/views'>;
}
declare module 'node-pg-migrate/lib/operations/viewsMaterialized.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/operations/viewsMaterialized'>;
}
declare module 'node-pg-migrate/lib/runner.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/runner'>;
}
declare module 'node-pg-migrate/lib/utils.js' {
  declare module.exports: $Exports<'node-pg-migrate/lib/utils'>;
}
