// flow-typed signature: 0b454f77bd525e1348e446b597f9e388
// flow-typed version: <<STUB>>/restify-cors-middleware_v^1.1.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify-cors-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify-cors-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify-cors-middleware/src/actual' {
  declare module.exports: any;
}

declare module 'restify-cors-middleware/src/constants' {
  declare module.exports: any;
}

declare module 'restify-cors-middleware/src' {
  declare module.exports: any;
}

declare module 'restify-cors-middleware/src/origin-matcher' {
  declare module.exports: any;
}

declare module 'restify-cors-middleware/src/preflight' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify-cors-middleware/src/actual.js' {
  declare module.exports: $Exports<'restify-cors-middleware/src/actual'>;
}
declare module 'restify-cors-middleware/src/constants.js' {
  declare module.exports: $Exports<'restify-cors-middleware/src/constants'>;
}
declare module 'restify-cors-middleware/src/index' {
  declare module.exports: $Exports<'restify-cors-middleware/src'>;
}
declare module 'restify-cors-middleware/src/index.js' {
  declare module.exports: $Exports<'restify-cors-middleware/src'>;
}
declare module 'restify-cors-middleware/src/origin-matcher.js' {
  declare module.exports: $Exports<'restify-cors-middleware/src/origin-matcher'>;
}
declare module 'restify-cors-middleware/src/preflight.js' {
  declare module.exports: $Exports<'restify-cors-middleware/src/preflight'>;
}
