// flow-typed signature: d501d083bdf2f785b1079772c5af8794
// flow-typed version: <<STUB>>/restify-errors_v^6.1.1/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify-errors/lib/baseClasses/HttpError' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/baseClasses/RestError' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/helpers' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/httpErrors' {
  declare module.exports: any;
}

declare module 'restify-errors/lib' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/makeConstructor' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/restErrors' {
  declare module.exports: any;
}

declare module 'restify-errors/lib/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify-errors/lib/baseClasses/HttpError.js' {
  declare module.exports: $Exports<'restify-errors/lib/baseClasses/HttpError'>;
}
declare module 'restify-errors/lib/baseClasses/RestError.js' {
  declare module.exports: $Exports<'restify-errors/lib/baseClasses/RestError'>;
}
declare module 'restify-errors/lib/helpers.js' {
  declare module.exports: $Exports<'restify-errors/lib/helpers'>;
}
declare module 'restify-errors/lib/httpErrors.js' {
  declare module.exports: $Exports<'restify-errors/lib/httpErrors'>;
}
declare module 'restify-errors/lib/index' {
  declare module.exports: $Exports<'restify-errors/lib'>;
}
declare module 'restify-errors/lib/index.js' {
  declare module.exports: $Exports<'restify-errors/lib'>;
}
declare module 'restify-errors/lib/makeConstructor.js' {
  declare module.exports: $Exports<'restify-errors/lib/makeConstructor'>;
}
declare module 'restify-errors/lib/restErrors.js' {
  declare module.exports: $Exports<'restify-errors/lib/restErrors'>;
}
declare module 'restify-errors/lib/serializer.js' {
  declare module.exports: $Exports<'restify-errors/lib/serializer'>;
}
