// flow-typed signature: 2c13e24f0908eecf17148892293d07a3
// flow-typed version: <<STUB>>/restify_v^8.0.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restify/lib/bunyan_helper' {
  declare module.exports: any;
}

declare module 'restify/lib/chain' {
  declare module.exports: any;
}

declare module 'restify/lib/deprecationWarnings' {
  declare module.exports: any;
}

declare module 'restify/lib/dtrace' {
  declare module.exports: any;
}

declare module 'restify/lib/errorTypes' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/binary' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/json' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/jsonp' {
  declare module.exports: any;
}

declare module 'restify/lib/formatters/text' {
  declare module.exports: any;
}

declare module 'restify/lib/helpers/chainComposer' {
  declare module.exports: any;
}

declare module 'restify/lib/http_date' {
  declare module.exports: any;
}

declare module 'restify/lib' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/accept' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/audit' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/authorization' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/bodyParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/bodyReader' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/bunyan' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/conditionalHandler' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/conditionalRequest' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/cpuUsageThrottle' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/date' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/fieldedTextBodyParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/formBodyParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/fullResponse' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/gzip' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/inflightRequestThrottle' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/jsonBodyParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/jsonp' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/metrics' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/multipartBodyParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/oauth2TokenParser' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/context' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/dedupeSlashes' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/pause' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/prePath' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/reqIdHeaders' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/strictQueryParams' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/pre/userAgent' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/query' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/requestExpiry' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/static' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/staticFiles' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/throttle' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/utils/hrTimeDurationInMs' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/utils/httpDate' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/utils/regex' {
  declare module.exports: any;
}

declare module 'restify/lib/plugins/utils/shallowCopy' {
  declare module.exports: any;
}

declare module 'restify/lib/request' {
  declare module.exports: any;
}

declare module 'restify/lib/response' {
  declare module.exports: any;
}

declare module 'restify/lib/router' {
  declare module.exports: any;
}

declare module 'restify/lib/routerRegistryRadix' {
  declare module.exports: any;
}

declare module 'restify/lib/server' {
  declare module.exports: any;
}

declare module 'restify/lib/upgrade' {
  declare module.exports: any;
}

declare module 'restify/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restify/lib/bunyan_helper.js' {
  declare module.exports: $Exports<'restify/lib/bunyan_helper'>;
}
declare module 'restify/lib/chain.js' {
  declare module.exports: $Exports<'restify/lib/chain'>;
}
declare module 'restify/lib/deprecationWarnings.js' {
  declare module.exports: $Exports<'restify/lib/deprecationWarnings'>;
}
declare module 'restify/lib/dtrace.js' {
  declare module.exports: $Exports<'restify/lib/dtrace'>;
}
declare module 'restify/lib/errorTypes.js' {
  declare module.exports: $Exports<'restify/lib/errorTypes'>;
}
declare module 'restify/lib/formatters/binary.js' {
  declare module.exports: $Exports<'restify/lib/formatters/binary'>;
}
declare module 'restify/lib/formatters/index' {
  declare module.exports: $Exports<'restify/lib/formatters'>;
}
declare module 'restify/lib/formatters/index.js' {
  declare module.exports: $Exports<'restify/lib/formatters'>;
}
declare module 'restify/lib/formatters/json.js' {
  declare module.exports: $Exports<'restify/lib/formatters/json'>;
}
declare module 'restify/lib/formatters/jsonp.js' {
  declare module.exports: $Exports<'restify/lib/formatters/jsonp'>;
}
declare module 'restify/lib/formatters/text.js' {
  declare module.exports: $Exports<'restify/lib/formatters/text'>;
}
declare module 'restify/lib/helpers/chainComposer.js' {
  declare module.exports: $Exports<'restify/lib/helpers/chainComposer'>;
}
declare module 'restify/lib/http_date.js' {
  declare module.exports: $Exports<'restify/lib/http_date'>;
}
declare module 'restify/lib/index' {
  declare module.exports: $Exports<'restify/lib'>;
}
declare module 'restify/lib/index.js' {
  declare module.exports: $Exports<'restify/lib'>;
}
declare module 'restify/lib/plugins/accept.js' {
  declare module.exports: $Exports<'restify/lib/plugins/accept'>;
}
declare module 'restify/lib/plugins/audit.js' {
  declare module.exports: $Exports<'restify/lib/plugins/audit'>;
}
declare module 'restify/lib/plugins/authorization.js' {
  declare module.exports: $Exports<'restify/lib/plugins/authorization'>;
}
declare module 'restify/lib/plugins/bodyParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/bodyParser'>;
}
declare module 'restify/lib/plugins/bodyReader.js' {
  declare module.exports: $Exports<'restify/lib/plugins/bodyReader'>;
}
declare module 'restify/lib/plugins/bunyan.js' {
  declare module.exports: $Exports<'restify/lib/plugins/bunyan'>;
}
declare module 'restify/lib/plugins/conditionalHandler.js' {
  declare module.exports: $Exports<'restify/lib/plugins/conditionalHandler'>;
}
declare module 'restify/lib/plugins/conditionalRequest.js' {
  declare module.exports: $Exports<'restify/lib/plugins/conditionalRequest'>;
}
declare module 'restify/lib/plugins/cpuUsageThrottle.js' {
  declare module.exports: $Exports<'restify/lib/plugins/cpuUsageThrottle'>;
}
declare module 'restify/lib/plugins/date.js' {
  declare module.exports: $Exports<'restify/lib/plugins/date'>;
}
declare module 'restify/lib/plugins/fieldedTextBodyParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/fieldedTextBodyParser'>;
}
declare module 'restify/lib/plugins/formBodyParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/formBodyParser'>;
}
declare module 'restify/lib/plugins/fullResponse.js' {
  declare module.exports: $Exports<'restify/lib/plugins/fullResponse'>;
}
declare module 'restify/lib/plugins/gzip.js' {
  declare module.exports: $Exports<'restify/lib/plugins/gzip'>;
}
declare module 'restify/lib/plugins/index' {
  declare module.exports: $Exports<'restify/lib/plugins'>;
}
declare module 'restify/lib/plugins/index.js' {
  declare module.exports: $Exports<'restify/lib/plugins'>;
}
declare module 'restify/lib/plugins/inflightRequestThrottle.js' {
  declare module.exports: $Exports<'restify/lib/plugins/inflightRequestThrottle'>;
}
declare module 'restify/lib/plugins/jsonBodyParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/jsonBodyParser'>;
}
declare module 'restify/lib/plugins/jsonp.js' {
  declare module.exports: $Exports<'restify/lib/plugins/jsonp'>;
}
declare module 'restify/lib/plugins/metrics.js' {
  declare module.exports: $Exports<'restify/lib/plugins/metrics'>;
}
declare module 'restify/lib/plugins/multipartBodyParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/multipartBodyParser'>;
}
declare module 'restify/lib/plugins/oauth2TokenParser.js' {
  declare module.exports: $Exports<'restify/lib/plugins/oauth2TokenParser'>;
}
declare module 'restify/lib/plugins/pre/context.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/context'>;
}
declare module 'restify/lib/plugins/pre/dedupeSlashes.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/dedupeSlashes'>;
}
declare module 'restify/lib/plugins/pre/pause.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/pause'>;
}
declare module 'restify/lib/plugins/pre/prePath.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/prePath'>;
}
declare module 'restify/lib/plugins/pre/reqIdHeaders.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/reqIdHeaders'>;
}
declare module 'restify/lib/plugins/pre/strictQueryParams.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/strictQueryParams'>;
}
declare module 'restify/lib/plugins/pre/userAgent.js' {
  declare module.exports: $Exports<'restify/lib/plugins/pre/userAgent'>;
}
declare module 'restify/lib/plugins/query.js' {
  declare module.exports: $Exports<'restify/lib/plugins/query'>;
}
declare module 'restify/lib/plugins/requestExpiry.js' {
  declare module.exports: $Exports<'restify/lib/plugins/requestExpiry'>;
}
declare module 'restify/lib/plugins/static.js' {
  declare module.exports: $Exports<'restify/lib/plugins/static'>;
}
declare module 'restify/lib/plugins/staticFiles.js' {
  declare module.exports: $Exports<'restify/lib/plugins/staticFiles'>;
}
declare module 'restify/lib/plugins/throttle.js' {
  declare module.exports: $Exports<'restify/lib/plugins/throttle'>;
}
declare module 'restify/lib/plugins/utils/hrTimeDurationInMs.js' {
  declare module.exports: $Exports<'restify/lib/plugins/utils/hrTimeDurationInMs'>;
}
declare module 'restify/lib/plugins/utils/httpDate.js' {
  declare module.exports: $Exports<'restify/lib/plugins/utils/httpDate'>;
}
declare module 'restify/lib/plugins/utils/regex.js' {
  declare module.exports: $Exports<'restify/lib/plugins/utils/regex'>;
}
declare module 'restify/lib/plugins/utils/shallowCopy.js' {
  declare module.exports: $Exports<'restify/lib/plugins/utils/shallowCopy'>;
}
declare module 'restify/lib/request.js' {
  declare module.exports: $Exports<'restify/lib/request'>;
}
declare module 'restify/lib/response.js' {
  declare module.exports: $Exports<'restify/lib/response'>;
}
declare module 'restify/lib/router.js' {
  declare module.exports: $Exports<'restify/lib/router'>;
}
declare module 'restify/lib/routerRegistryRadix.js' {
  declare module.exports: $Exports<'restify/lib/routerRegistryRadix'>;
}
declare module 'restify/lib/server.js' {
  declare module.exports: $Exports<'restify/lib/server'>;
}
declare module 'restify/lib/upgrade.js' {
  declare module.exports: $Exports<'restify/lib/upgrade'>;
}
declare module 'restify/lib/utils.js' {
  declare module.exports: $Exports<'restify/lib/utils'>;
}
