// flow-typed signature: 4ba76dc60a2febb12400f9cf42154334
// flow-typed version: <<STUB>>/squel_v^5.12.2/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'squel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'squel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'squel/dist/squel-basic' {
  declare module.exports: any;
}

declare module 'squel/dist/squel-basic.min' {
  declare module.exports: any;
}

declare module 'squel/dist/squel' {
  declare module.exports: any;
}

declare module 'squel/dist/squel.min' {
  declare module.exports: any;
}

declare module 'squel/gulpfile' {
  declare module.exports: any;
}

declare module 'squel/performance/select' {
  declare module.exports: any;
}

// Filename aliases
declare module 'squel/dist/squel-basic.js' {
  declare module.exports: $Exports<'squel/dist/squel-basic'>;
}
declare module 'squel/dist/squel-basic.min.js' {
  declare module.exports: $Exports<'squel/dist/squel-basic.min'>;
}
declare module 'squel/dist/squel.js' {
  declare module.exports: $Exports<'squel/dist/squel'>;
}
declare module 'squel/dist/squel.min.js' {
  declare module.exports: $Exports<'squel/dist/squel.min'>;
}
declare module 'squel/gulpfile.js' {
  declare module.exports: $Exports<'squel/gulpfile'>;
}
declare module 'squel/performance/select.js' {
  declare module.exports: $Exports<'squel/performance/select'>;
}
