// flow-typed signature: ccab41f71d5f13e5e472440c23a4969d
// flow-typed version: <<STUB>>/to-array-buffer_v^3.2.0/flow_v0.106.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-array-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-array-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-array-buffer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-array-buffer/index' {
  declare module.exports: $Exports<'to-array-buffer'>;
}
declare module 'to-array-buffer/index.js' {
  declare module.exports: $Exports<'to-array-buffer'>;
}
declare module 'to-array-buffer/test.js' {
  declare module.exports: $Exports<'to-array-buffer/test'>;
}
